Trying to make PHPCS and PHPMD run in parallel.

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -7,13 +7,13 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: PHPCS
-      run: composer install && ./vendor/bin/phpcs -i && ./vendor/bin/phpcs --standard=WordPress --report=junit --report-file=./report.xml src
-    - uses: dorny/test-reporter@v1
-      if: success() || failure()        # run this step even if previous step failed
-      with:
-        name: PHPCS Results         # Name of the check run which will be created
-        path: ./report.xml          # Path to test results
-        reporter: java-junit        # Format of test results
+      run: composer install && ./vendor/bin/phpcs -i && ./vendor/bin/phpcs --standard=WordPress --report=junit src
+    # - uses: dorny/test-reporter@v1
+    #   if: success() || failure()        # run this step even if previous step failed
+    #   with:
+    #     name: PHPCS Results         # Name of the check run which will be created
+    #     path: ./report.xml          # Path to test results
+    #     reporter: java-junit        # Format of test results
 
   md:
     name: PHP Mess Detector 🧹
